project_id = "hptflpqaskbuzivynjvb"

[functions.get-questions]
verify_jwt = false

[functions.get-followups]
verify_jwt = false

[functions.seed-questions]
verify_jwt = false

[functions.create-print-checkout]
verify_jwt = true