project_id = "hptflpqaskbuzivynjvb"

[functions.send-email]
verify_jwt = false

[functions.send-waitlist-email]
verify_jwt = false

[functions.get-questions]
verify_jwt = false

[functions.get-followups]
verify_jwt = false

[functions.seed-questions]
verify_jwt = false

[functions.create-print-checkout]
verify_jwt = true

[functions.delete-book-deep]
verify_jwt = true

[functions.delete-session-deep]
verify_jwt = true

[functions.send-gift-invitation]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-plan-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
