project_id = "hptflpqaskbuzivynjvb"

[functions.get-questions]
verify_jwt = false

[functions.get-followups]
verify_jwt = false

[functions.seed-questions]
verify_jwt = false

[functions.transcribe-session]
verify_jwt = true

[functions.generate-book-pdf]
verify_jwt = true
