project_id = "hptflpqaskbuzivynjvb"

[functions.get-questions]
verify_jwt = false

[functions.get-followups]
verify_jwt = false

[functions.seed-questions]
verify_jwt = false

[functions.suggest-questions]
verify_jwt = false